### PR TITLE
Let's start 2018

### PR DESCRIPTION
**Pull request by thedamian**
- SUGGESTED a day
- Creating 2018
- Adding the cities I know are already ready
- Making suggestions to changes to the front page (resetting the cities)
- Updating the GeoJSON file to include the two cities that are ready!

### CODE REVIEW

**Comment by dtex** [comment]
The date seems like a good one to me, but note that it's the last day of NodeSummit. Some potential organizers may still be traveling back from the Bay Area that weekend.

**Comment by thedamian** [comment]
Although I agree. At the same time it might be a GREAT day since there will have been a lot of hype over the last couple of days. And maybe it can give THAT conference a chance to make it an EXTRA day later for kids to learn to use their skills playing with ROBOTS!

**Comment by dshaw** [comment]
@thedamian July 28th this year? Happy to help find space in SF. The conference center where Node Summit is not rented out anymore at that time. If there's interest in exploring something on the 27th, I might be able to help though.

**Comment by thedamian** [comment]
The 28th is simply a suggestion because it was the saturday closest to last years date (the 29th)

The 27th would be a friday. I was simply suggesting that that having it the NEXT day AFTER the Node Conference might be beneficial as oppose to what @dtex 

Just getting the discussion started.

**Comment by lynnaloo** [comment]
The date is usually the last Saturday in July and then *most* of the cities try to hold it on that day. There is always a handful of organizers that can't make it work and do a week before or after.

**Pull request merged**
