### PR TITLE
NodeBots Day 2017 for Kerala, INDIA, IN!

### PR DESCRIPTION
**Pull request by salmanfarisvp**

### CODE REVIEW

**Comment by dtex** [comment]
Welcome @salmanfarisvp 

There seems to be a problem with the home page link

**Comment by salmanfarisvp** [comment]
home page work is not completed , so i just put that dummy link..

**Comment by dtex** [comment]
I don't know of any templates, but you are welcome to clone [the repo](https://github.com/NodejsHouston/bots) for our [Houston page](https://nodejshouston.github.io/bots/) and modify that. I imagine the other hosts would be similarly inclined (check their licenses).

**Comment by dtex** [comment]
I'm gonna merge, but am going to change that link to "soon" so people don't get frustrated

**Comment by salmanfarisvp** [comment]
Ok, Thanks 👍 :

**Pull request merged**
