### PR TITLE
Update events.geojson

### PR DESCRIPTION
**Pull request by PT1ATE**

### CODE REVIEW

**Comment by dtex** [comment]
Hi there @PT1ATE I haven't merged this yet because there are a few more things that need to be added. You'll want to add your even to the readme at the root, and then copy the _template folder in 2017 and use that to create a new folder for your event.

**Comment by PT1ATE** [comment]
[Mexico City.zip](https://github.com/nodebots/nodebotsday/files/1114057/Mexico.City.zip)

**Comment by PT1ATE** [comment]
Add Mexico City README

**Comment by dtex** [comment]
This was handled by #266

**Pull request closed without merging**
