### PR TITLE
Create event 

### PR DESCRIPTION
**Pull request by sprintnt**

### CODE REVIEW

**Comment by dtex** [comment]
Hi @sprintnt 

I'm excited to see another event added. I haven't merged this yet because you will also need to update the readme.md in the root, and add your location in the events.geojson file.

Check out #252 for a good example.

**Comment by sprintnt** [comment]
Hi @dtex 
I updated readme.md in the root. It's OK. But, I have a problem with events.geojson to determine point. I put GPS coordinate, but mark point somewhere in Saudi Arabia ....

**Comment by dtex** [comment]
I think you just have your latitude and longitude swapped. Try this:

````javascript
"coordinates": [		
  19.84444,    \\ latitude
  45.24953     \\ longitude		
]
````

**Comment by sprintnt** [comment]
That's true, I swapped longitude and latitude... Now it's correct

**Pull request merged**
