### PR TITLE
Updated Information from Norfolk

### PR DESCRIPTION
**Pull request by lynnaloo**

### CODE REVIEW

**Comment by olizilla** [comment]
Woo! Go Norfolk!

**Comment by olizilla** [comment]
@lynnaloo just a quick question, did you mean to revise the info for the **2014**, or are you updating for **2015**? 

@dshaw I guess we should archive the 2014 details now, right?

**Comment by onel0p3z** [comment]
+1 for archiving @olizilla ... modifying the info from 2014 had me thinking/confused the same yesterday :confused:

**Comment by lynnaloo** [comment]
Someone had already updated the title to 2015 so I just changed the rest of the info as well. Last year, it was a change rather than an archive.

**Comment by olizilla** [comment]
@lynnaloo I'm all for updated info! Let's merge this. The rest of the page will be updated nearer the time and git is all archive we need right now. ;-)

**Comment by lynnaloo** [comment]
I'll do more PRs as we get more sponsors and volunteers, but I'm starting early with the planning :)

**Pull request merged**
